-- Create cases table for storing patient cases
CREATE TABLE IF NOT EXISTS `cases` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `patient_name` VARCHAR(255) NOT NULL,
  `patient_id` VARCHAR(50) NOT NULL,
  `date` VARCHAR(50) NOT NULL,
  `surgery_type` VARCHAR(255) NOT NULL,
  `anesthetic_agent` VARCHAR(255) NOT NULL,
  `molecular_mass` VARCHAR(50) NOT NULL,
  `vapor_constant` VARCHAR(50) NOT NULL,
  `density` VARCHAR(50) NOT NULL,
  `fresh_gas_flow` DOUBLE NULL,
  `dial_concentration` DOUBLE NULL,
  `time_minutes` DOUBLE NULL,
  `initial_weight` DOUBLE NULL,
  `final_weight` DOUBLE NULL,
  `biro_formula` DOUBLE NULL,
  `dion_formula` DOUBLE NULL,
  `weight_based` DOUBLE NULL,
  `notes` TEXT NULL,
  `induction_fgf` DOUBLE NULL,
  `induction_concentration` DOUBLE NULL,
  `induction_time` DOUBLE NULL,
  `induction_biro` DOUBLE NULL,
  `induction_dion` DOUBLE NULL,
  `final_biro` DOUBLE NULL,
  `final_dion` DOUBLE NULL,
  `maintenance_rows` LONGTEXT NULL,
  `maintenance_calculations` LONGTEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_patient_id` (`patient_id`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
